spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.240:31500/realms/anurag
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8087

jwt:
  auth:
    converter:
      resource-id: niral_api
      principle-attribute: preferred_username
